source 'https://rubygems.org'
require 'json'
require 'open-uri'
# Middleman
gem 'middleman', '~>4.0.0'
gem 'middleman-gh-pages', '~> 0.0.3'
gem 'middleman-syntax', '~> 2.1.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem "middleman-sprockets", "~> 4.0.0.rc"
gem 'rouge', '~> 1.10.1'
gem "middleman-livereload", "~> 3.4.3"
gem 'redcarpet', '~> 3.3.2'
gem "middleman-deploy", "~> 2.0.0.pre.alpha"
gem 'github-pages'


versions = JSON.parse(open('https://pages.github.com/versions.json').read)
